name: Build and Push Housing Management Image

on:
  push:
    branches:
      - '**'
    paths:
      - "packages/housing-management/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      id-token: write  # necesario para OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if not exists
        run: |
            aws ecr describe-repositories --repository-names residium/housing-management || \
            aws ecr create-repository --repository-name residium/housing-management

      - name: Build Docker image
        run: |
          docker build \
            -t residium/housing-management:${{ github.run_number }} \
            -t residium/housing-management:latest \
            -f packages/housing-management/Dockerfile \
            .

      - name: Tag Docker image for ECR
        run: |
          docker tag residium/housing-management:${{ github.run_number }} public.ecr.aws/${{ secrets.ECR_REGISTRY }}/residium/housing-management:${{ github.run_number }}
          docker tag residium/housing-management:latest public.ecr.aws/${{ secrets.ECR_REGISTRY }}/residium/housing-management:latest

      - name: Push Docker image to ECR
        run: |
          docker push public.ecr.aws/${{ secrets.ECR_REGISTRY }}/residium/housing-management:${{ github.run_number }}
          docker push public.ecr.aws/${{ secrets.ECR_REGISTRY }}/residium/housing-management:latest
