name: Push Housing Management Image

on:
  workflow_run:
    workflows: ["Build Housing Management Image"]
    types:
      - completed

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # necesario para OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: |
          docker tag tikitup/housing-management:${{ github.run_number }} ${{ secrets.ECR_REGISTRY }}/tikitup/housing-management:${{ github.run_number }}
          docker tag tikitup/housing-management:latest ${{ secrets.ECR_REGISTRY }}/tikitup/housing-management:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/tikitup/housing-management:${{ github.run_number }}
          docker push ${{ secrets.ECR_REGISTRY }}/tikitup/housing-management:latest
